class Key:
    """
    Class for keeping global keys that are shared across different modules.
    """
    TITLE = "title"
    QUESTIONS = "questions"
    QUESTION_ID = "question_id"
    ANSWERS = "answers"
    ANSWER_TEXT = "answer_text"
    QUESTION_TEXT = "question_text"
    ANSWER_ID = "answer_id"
    NEXT_QUEST_ID = "next_question_id"
    QUESTIONNAIRE_ID = "questionnaire_id"
    ERROR = "error"
    TRACK = "track"
    STRING_ERROR_QUESTION_ID = "No question found with this id"
    STRING_ERROR_ANSWER_ID = "No answer found with this id"
    STRING_ERROR_QUESTIONNAIRE_ID = "No questionnaire found with this id"
    STRING_ERROR_NO_QUESTIONNAIRES = "No questionnaires are found "
