# Generated by Django 2.2.3 on 2019-08-11 06:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='questions',
            old_name='question_text',
            new_name='title',
        ),
    ]
