# Generated by Django 2.2.3 on 2019-08-11 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0002_auto_20190811_1117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questions',
            name='first_question',
            field=models.BooleanField(default=False),
        ),
    ]
