# Generated by Django 2.2.3 on 2019-08-11 08:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0003_auto_20190811_1259'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answers',
            old_name='text',
            new_name='title',
        ),
    ]
